---
- name: Deploy using shell modules
  hosts: 172.18.35.50
  tasks:
    - name: Docker Deployment Via BASH
      shell: docker_init.sh >> /usr/scripts/initLog.txt

    - name: yum refresh of assets
      yum:
        name: '*'
        state: latest
  
    - name: Pull images for docker
      shell: docker pull linode/lamp
  
    - name: Run LAMP w/ port 80 forwarded
      shell: docker run -p 80:80 linode/lamp /bin/bash
  
    - name: Start apache and other mods
      shell: docker exec service apache2 start
  
    - name: Start Mysql
      shell: docker exec service mysql start
